# Generated by Django 5.1.6 on 2025-03-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_follow_followed_alter_follow_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
    ]
